### ISSUE TITLE
Billing > invoices not deleted

### ISSUE THREAD

**Issue by Ninjeneer** [sap-labs-france/ev-server#1886] opened 2020-11-05 12:26 UTC
Local invoices are not deleted during sync, while Stripe invoices are.

**Comment by ClaudeROSSI** [comment] 2021-05-24 06:04
@Ninjeneer : Hi Loan, do you remember the purpose of that old ev-server issue (from November last year)?
Thanks

**Comment by Ninjeneer** [comment] 2021-05-24 11:22
Hi @ClaudeROSSI, if I remember well, if you delete an invoice on the Stripe side, and then run a sync on e-Mobility, the e-Mobility invoice is not deleted.
But I think it is already fixed

**Comment by ClaudeROSSI** [comment] 2021-05-24 14:59
@Ninjeneer : Thanks for the reply.

I think the issue does not match anymore the STRIPE integration as it is today. 

First of all, it is important to have in mind that invoices cannot be deleted on the stripe side when running in a productive environment. In other words, the issue is meaningless in the real context.

Anyway, the logic has been changed completely. Invoices that are visible on the eMobility side are the ones corresponding to an EV charging session (i.e.: a transaction). Invoices created manually on the stripe side (by selling some other products) are not replicated / nor visible in the eMobility database. As a consequence the deletion topic does not apply anymore.

I'll close this issue.
Let me know if you have a different view on the initial concern.

**Closed by ClaudeROSSI** 2021-05-24 14:59 UTC
Labels: bug
